---
apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nodetodo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nodetodo
    spec:
      containers:
      - name: nodetodo
        image: nodehelloimg
        imagePullPolicy: "Never"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: "/health"
            port: 3000
          initialDelaySeconds: 300
          periodSeconds: 5
          failureThreshold: 45
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: "/health"
            port: 3000
          initialDelaySeconds: 300
          periodSeconds: 5
          failureThreshold: 45
---
apiVersion: v1
kind: Service
metadata:
  name: nodetodo
spec:
  selector:
    app: nodetodo
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer